
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'pumphouse'
          scrape_interval: 30s
          static_configs:
            - targets: ['192.168.0.60:8888']
  otelarrow:
    protocols:
      grpc:
        endpoint: 192.168.0.40:4317

processors:

exporters:
  otlp:
    endpoint: ingest.lightstep.com:443
    headers:
    - lightstep-access-token: ${env:LIGHTSTEP_TOKEN}
  jsonfile:
    path: "/home/data/casparwater.json"
  influxdb:
    endpoint: https://casparwater.us:8086
    org: casparwater
    bucket: production
    token: ${env:INFLUXD_TOKEN}

service:
  pipelines:
    metrics:
      receivers:
      - prometheus
      - otelarrow
      processors: []
      exporters:
      - otlp
      - jsonfile
      - influxdb
  telemetry:
    logs:
      level: debug
    metrics:
      level: none


