
receivers:
  atlasph:
  sparkplug:
    broker:
      host_id: waterco
      self_hosted: true
      endpoint: :1883
    metrics:
      - well_depth_value
      - system_pressure_value
      - chlorine_level_value
      - concrete_tank_level_value

exporters:
  otelarrow:
    endpoint: 192.168.0.40:4317
    tls:
      insecure: true
    timeout: 1m
    arrow:
      num_streams: 1
      max_stream_lifetime: 1hr

service:
  pipelines:
    metrics:
      receivers:
      - atlasph
      - sparkplug
      processors: []
      exporters:
      - otelarrow
  telemetry:
    logs:
      level: debug
    metrics:
      level: none
