
receivers:
  atlasph:
  sparkplug:
    broker:
      host_id: waterco
      self_hosted: true
      endpoint: :1883
    metrics:
      - well_depth_value
      - system_pressure_value
      - chlorine_level_value
      - concrete_tank_level_value

exporters:
  otlp:
    endpoint: 192.168.0.40:4317
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers:
      - atlasph
      - sparkplug
      processors: []
      exporters:
      - otlp
  telemetry:
    logs:
      level: debug
    metrics:
      level: none
