
receivers:
  bme280:
    device: "/dev/i2c-5"
    i2c_addr: 0x77
    interval: "60s"
    prefix: "septicstation"

exporters:
  debug:
    verbosity: detailed
  jsonfile:
    path: "/home/data/septicstation.json"

service:
  pipelines:
    metrics:
      receivers:
      - bme280
      exporters:
      - jsonfile
      - debug
  telemetry:
    logs:
      level: debug
    metrics:
      level: none
