
receivers:
  bme280:
    device: "/dev/i2c-5"
    i2c_addr: "0x77"
    interval: "60s"
    prefix: "wellkit"
  modbus:
    url: "rtu:///dev/ttyUSB0"
    prefix: "wellprobe"
    interval: "60s"
    attributes:
    - name: "serial_number"
      base: 9002
      type: "uint32"
      range: "holding"
    metrics:
    - name: "pressure"
      base: 38
      type: "float32"
      range: "holding"
      unit: "psi"
    - name: "temperature"
      base: 46
      type: "float32"
      range: "holding"
      unit: "C"

exporters:
  openlcd:
    device: "/dev/i2c-5"
    i2c_addr: "0x72"
    run_for: 10m
    refresh: 5s
    staleness: 2m
    show:
    - metric: wellkit_temperature
      abbrev: temp
    - metric: wellkit_pressure
      abbrev: atmos
    - metric: wellkit_humidity
      abbrev: humid
    - metric: wellprobe_pressure
      abbrev: depth
    - metric: wellprobe_temperature
      abbrev: wtemp
  influxdb:
    endpoint: https://casparwater.us:8086
    org: ${env:INFLUX_ORG}
    bucket: ${env:INFLUX_BUCKET}
    token: ${env:INFLUX_TOKEN}

processors:
  units:
    replace:
    - input: "Pa"
      output: "psi"
      conversion: 0.0001450377
  batch:
    send_batch_size: 500
    timeout: 5m

connectors:
  forward:

service:
  pipelines:
    # The arrangement of 3 pipelines w/ a forwarding connector
    # allows the display to be immediate while the influxdb export
    # is delayed by the batcher.
    metrics/produce:
      receivers:
        - bme280
        - modbus
      processors:
        - units
      exporters:
        - forward

    metrics/egress:
      receivers:
        - forward
      processors:
        - batch
      exporters:
        - influxdb

    metrics/display:
      receivers:
        - forward
      exporters:
        - openlcd


