
receivers:
  serial:
    device: /dev/ttyUSB0
    baud: 115200

exporters:
  debug:
  otelarrow:
    endpoint: 192.168.0.40:4317
    tls:
      insecure: true
    timeout: 1m
    arrow:
      num_streams: 1
      max_stream_lifetime: 1h

service:
  pipelines:
    logs:
      receivers:
      - serial
      exporters:
      - otelarrow
      - debug
  telemetry:
    logs:
      level: debug
    metrics:
      level: none
