factory: sitegen

site:
  title: "Caspar Water"
  base_url: "${env:SITE_BASE_URL:-/}"
  site_url: "https://casparwater.us"
  github_url: "https://github.com/jmacd/duckpond"

content:
  - name: "pages"
    pattern: "/content/*.md"

exports:
  - name: "metrics"
    pattern: "/reduced/*/*/*.series"
  - name: "analysis"
    pattern: "/analysis/*"

routes:
  - name: "home"
    type: static
    slug: ""
    page: "/site/index.md"
    routes:
      - name: "pages"
        type: content
        slug: ""
        content: "pages"
      - name: "data"
        type: static
        slug: "data"
        routes:
          - name: "metric-detail"
            type: template
            slug: "$0"
            page: "/site/data.md"
            export: "metrics"
      - name: "analysis"
        type: static
        slug: "analysis"
        routes:
          - name: "analysis-detail"
            type: template
            slug: "$0"
            page: "/site/analysis.md"
            export: "analysis"

partials:
  sidebar: "/site/sidebar.md"

static:
  - pattern: "/img/*"

theme:
  bg-image: "url('${env:SITE_BASE_URL:-/}img/logo.svg')"

sidebar:
  - "Political"
  - "Blog"
  - "History"
  - "Water"
  - label: "System"
    children:
      - label: "Pump Cycles"
        href: "${env:SITE_BASE_URL:-/}analysis/pump-cycles.html"
  - label: "Monitoring"
    children:
      - label: "Well Depth"
        href: "${env:SITE_BASE_URL:-/}data/well-depth.html"
      - label: "Tank Level"
        href: "${env:SITE_BASE_URL:-/}data/tank-level.html"
      - label: "System Pressure"
        href: "${env:SITE_BASE_URL:-/}data/system-pressure.html"
      - label: "Chlorine Level"
        href: "${env:SITE_BASE_URL:-/}data/chlorine-level.html"
      - label: "pH"
        href: "${env:SITE_BASE_URL:-/}data/ph.html"
  - "Software"
  - "Operator"
  - "Thanks"
