dist:
  name: watermon
  description: Water monitoring collector
  output_path: build
  otelcol_version: 0.72.0

exporters:
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/storage/fileexporter
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/display/matrixfruit
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.72.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.72.0

receivers:
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/measure/currentloop
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/sparkplug/sparkplugreceiver

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.72.0

replaces:
  - github.com/jmacd/caspar.water => ../../
