dist:
  name: watermon
  description: Water monitoring collector
  output_path: build
  otelcol_version: 0.81.0

exporters:
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/storage/fileexporter
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/storage/influxdbexporter
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/display/matrixfruit
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/display/openlcd
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.81.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.81.0

receivers:
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/measure/currentloop
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/measure/bme280
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/measure/modbus
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/sparkplug/sparkplugreceiver
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.81.0

processors:
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/display/units
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.81.0

connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.81.0


replaces:
  - github.com/jmacd/caspar.water => ../../
  - github.com/jmacd/caspar.water/measure/bme280 => ../../measure/bme280
  - github.com/jmacd/caspar.water/measure/modbus => ../../measure/modbus
  - github.com/jmacd/caspar.water/display/openlcd => ../../display/openlcd
