dist:
  name: watermon
  description: Water monitoring collector
  output_path: ./build
  module: github.com/jmacd/caspar.water/collector/build
  otelcol_version: 0.111.0

exporters:
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/storage/jsonfileexporter
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/storage/influxdbexporter
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/display/matrixfruit
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/display/openlcd
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.111.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.111.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/otelarrowexporter v0.111.0

receivers:
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/measure/currentloop
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/measure/bme280
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/measure/modbus
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/sparkplug/sparkplugreceiver
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/measure/ph/atlasph
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/storage/serialreceiver
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.111.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.111.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/otelarrowreceiver v0.111.0

processors:
  - gomod: github.com/jmacd/caspar.water v0.0.0
    import: github.com/jmacd/caspar.water/display/units
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.111.0

connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.111.0


replaces:
  - github.com/jmacd/caspar.water => ../../
  - github.com/jmacd/caspar.water/storage/serialreceiver => ../../storage/serialreceiver
  - github.com/jmacd/caspar.water/storage/jsonfileexporter => ../../storage/jsonfileexporter
  - github.com/jmacd/caspar.water/storage/influxdbexporter => ../../storage/influxdbexporter
  - github.com/jmacd/caspar.water/measure/bme280 => ../../measure/bme280
  - github.com/jmacd/caspar.water/measure/currentloop => ../../measure/currentloop
  - github.com/jmacd/caspar.water/measure/modbus => ../../measure/modbus
  - github.com/jmacd/caspar.water/measure/ph/atlasph => ../../measure/ph/atlasph
  - github.com/jmacd/caspar.water/display/openlcd => ../../display/openlcd
  - github.com/jmacd/caspar.water/display/matrixfruit => ../../display/matrixfruit
  - github.com/jmacd/caspar.water/sparkplug/sparkplugreceiver => ../../sparkplug/sparkplugreceiver
