
receivers:
  sparkplug:
    broker:
      host_id: waterco
      self_hosted: true
      endpoint: :1883
    metrics:
      - pid_temperature_value
      - well_depth_value
      - tank_level_value
      - chlorine_level_value
  prometheus:
    config:
      scrape_configs:
        - job_name: 'upperwell'
          scrape_interval: 30s
          static_configs:
            - targets: ['192.168.0.80:8888']

processors:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: ingest.lightstep.com:443
    headers:
    - lightstep-access-token: 4IY1I9adf9FeOUUFgHiOaWIp4hRs1NDlwQfyzV02oRA+/3PBGchUJ0MoQkHKuxQcHC/+AYLM5k7iVboj5A6NP12eVjICe9+yQOT9bNsv
  jsonfile:
    path: "/home/data/casparwater.json"

service:
  pipelines:
    metrics:
      receivers:
      - sparkplug
      - prometheus
      processors: []
      exporters:
      - otlp
      - jsonfile
  telemetry:
    logs:
      level:
        debug
