
receivers:
  bme280:
    device: "/dev/i2c-5"
    i2c_addr: "0x77"
    interval: "60s"
    prefix: "wellkit"
  modbus:
    url: "rtu:///dev/ttyUSB0"
    prefix: "wellprobe"
    interval: "60s"
    attributes:
    - name: "serial_number"
      base: 9002
      type: "uint32"
      range: "holding"
    metrics:
    - name: "temperature"
      base: 38
      type: "float32"
      range: "holding"
      unit: "C"
    - name: "pressure"
      base: 46
      type: "float32"
      range: "holding"
      unit: "psi"

exporters:
  openlcd:
    device: "/dev/i2c-5"
    i2c_addr: "0x72"
    show:
    - metric: wellkit_temperature
      abbrev: temp
    - metric: wellkit_pressure
      abbrev: atmos
    - metric: wellkit_humidity
      abbrev: humid
    - metric: wellprobe_pressure
      abbrev: depth
  influxdb:
    endpoint: https://casparwater.us:8086

processors:
  units:
    replace:
    - input: "Pa"
      output: "psi"
      conversion: 0.0001450377
  batch:
    send_batch_size: 100
    timeout: 30s

service:
  pipelines:
    metrics:
      receivers:
        - bme280
        - modbus
      processors:
        - units
        - batch
      exporters:
        - openlcd
        - influxdb
