
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:55680
  sparkplug:
    broker:
      host_id: waterco
      self_hosted: true
      endpoint: :1883

processors:

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers:
        - otlp
        - sparkplug
      processors: []
      exporters:
        - logging
