
receivers:
  sparkplug:
    broker:
      host_id: waterco
      self_hosted: true
      endpoint: :1883

processors:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: ingest.lightstep.com:443
    headers:
    - lightstep-access-token: 4IY1I9adf9FeOUUFgHiOaWIp4hRs1NDlwQfyzV02oRA+/3PBGchUJ0MoQkHKuxQcHC/+AYLM5k7iVboj5A6NP12eVjICe9+yQOT9bNsv
  jsonfile:
    path: "/home/data/casparwater.json"

service:
  pipelines:
    metrics:
      receivers:
        - sparkplug
      processors: []
      exporters:
        - otlp
        - jsonfile
