
receivers:
  bme280:
    device: "/dev/i2c-5"
    i2c_addr: "0x77"
    interval: "5s"
    prefix: "wellkit"

exporters:
  openlcd:
    device: "/dev/i2c-5"
    i2c_addr: "0x72"
    metrics:
    - wellkit_temperature
    - wellkit_pressure
    - wellkit_humidity

  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers:
        - bme280
      exporters:
        - openlcd
        - logging
