
receivers:
  bme280:
    device: "/dev/i2c-5"
    i2c_addr: "0x77"
    interval: "5s"
    prefix: "wellkit"

exporters:
  openlcd:
    device: "/dev/i2c-5"
    i2c_addr: "0x72"
    show:
    - metric: wellkit_temperature
      abbrev: temp
    - metric: wellkit_pressure
      abbrev: atmos
    - metric: wellkit_humidity
      abbrev: humid

processors:
  units:
    replace:
    - input: "Pa"
      output: "psi"
      conversion: 0.0001450377

service:
  pipelines:
    metrics:
      receivers:
        - bme280
      processors:
        - units
      exporters:
        - openlcd
